import { z } from 'zod';

export const RibbonZoneSchema = z.enum(['primary-status', 'secondary-highlight']);
export const RibbonTypeSchema = z.enum([
  'for-sale',
  'sold',
  'breeder',
  'retained',
  'birthday',
  'featured',
  'new-calf',
  'auction',
]);

export const RibbonFlagSchema = z.object({
  zone: RibbonZoneSchema,
  type: RibbonTypeSchema,
  label: z.string(),
  priority: z.number(),
  autoGenerated: z.boolean(),
});

export const NudgePrioritySchema = z.enum(['high', 'medium', 'low']);
export const NudgeTypeSchema = z.enum([
  'missing-side',
  'missing-head',
  'missing-three-quarter',
  'stale-card-imagery',
  'low-confidence-pending',
  'unbranded',
  'missing-basics',
  'sale-no-photo',
  'pregnancy-overdue',
  'multiple-calves-same-dam',
]);

export const NudgeFlagSchema = z.object({
  type: NudgeTypeSchema,
  priority: NudgePrioritySchema,
  label: z.string(),
  animalId: z.string().uuid(),
});

export const DerivedCattleStateSchema = z.object({
  animalId: z.string().uuid(),
  canonicalViews: z.object({
    sideMediaId: z.string().uuid().nullable(),
    headMediaId: z.string().uuid().nullable(),
    threeQuarterMediaId: z.string().uuid().nullable(),
    completeness: z.union([z.literal(0), z.literal(1), z.literal(2), z.literal(3)]),
    lastRefreshedAt: z.string(),
  }),
  timeline: z.object({
    firstPhotoDate: z.string().nullable(),
    latestPhotoDate: z.string().nullable(),
    publicPhotoCount: z.number().int().nonnegative(),
  }),
  nudges: z.array(NudgeFlagSchema),
  ribbons: z.array(RibbonFlagSchema),
});

export type DerivedCattleState = z.infer<typeof DerivedCattleStateSchema>;
export type RibbonFlag = z.infer<typeof RibbonFlagSchema>;
export type RibbonZone = z.infer<typeof RibbonZoneSchema>;
export type RibbonType = z.infer<typeof RibbonTypeSchema>;
export type NudgeFlag = z.infer<typeof NudgeFlagSchema>;
export type NudgePriority = z.infer<typeof NudgePrioritySchema>;
export type NudgeType = z.infer<typeof NudgeTypeSchema>;
